[package]
name = "api-server"
version = "0.1.0"
authors = ["soeur <1034236490@qq.com>"]
edition = "2018"

[dependencies]
websocket = "0.22.0"
bcrypt = "0.2.1"
timer = "0.2.0"
chrono = "0.4.6"
config = "0.9.2"
lazy_static = "1.2.0"
log = "0.4.6"
simplelog = "0.5.3"